
[window]
decorations = "None"
blur = true
startup_mode = "Maximized"
opacity = 0.9

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000
multiplier = 2

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"
size = 10

[cursor]
style.shape = "Beam"
style.blinking = "On"

[terminal.shell]
program = "zsh"

[keyboard]
bindings = [{ key = "Slash", mods = "Control", chars = "\u001f" }]

[terminal]
